spring:
    application:
        name: BookLibrary
    # PostgreSQL DB
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        database: POSTGRESQL
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        # create-drop means the database is fresh on each restart
        hibernate:
            ddl-auto: update